name: ffms2

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  format-and-tests:
    strategy:
      matrix:
        conf:
          - clippy-rustfmt
          - ffms2-tests
        include:
          - conf: clippy-rustfmt
            components: clippy, rustfmt

    runs-on: ubuntu-latest
    container: shssoichiro/av1an-ci:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: ${{ matrix.components }}

      - uses: Swatinem/rust-cache@v2

      - name: Run rustfmt
        if: matrix.conf == 'clippy-rustfmt'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Run clippy
        if: matrix.conf == 'clippy-rustfmt'
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- -D warnings

      - name: Run tests
        if: matrix.conf == 'ffms2-tests'
        uses: actions-rs/cargo@v1
        with:
          command: test
